name: Olympus
version: ${project.version}
main: us.olympusmc.olympus.Olympus
api-version: 1.17
authors: [ MrScopes ]
description: Plugin made for OlympusMC
website: https://github.com/MrScopes/Olympus
commands:
  color:
    description: Change your username color.
    usage: You must choose a support color.
  name:
    description: Set your ingame name.